//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionManagementWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int account_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> is_activated { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
