//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionManagementWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Delivery_Note
    {
        public int delivery_id { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string delivery_method { get; set; }
    
        public virtual Order_Note Order_Note { get; set; }
    }
}
