//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionManagementWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Received_Note
    {
        public int received_id { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string received_from { get; set; }
        public Nullable<int> total_quantity { get; set; }
        public Nullable<int> total_cost { get; set; }
    
        public virtual Received_Item Received_Item { get; set; }
    }
}
