//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionManagementWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Note
    {
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> reseller_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public string payment_method { get; set; }
    
        public virtual Goods_Delivery_Note Goods_Delivery_Note { get; set; }
        public virtual Order_Item Order_Item { get; set; }
        public virtual Reseller Reseller { get; set; }
        public virtual Status Status { get; set; }
    }
}
