//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionManagementWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Received_Item
    {
        public int received_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> cost_per_unit { get; set; }
    
        public virtual Goods_Received_Note Goods_Received_Note { get; set; }
        public virtual Product Product { get; set; }
    }
}
